-- -- Create databases and schemas
-- create database if not exists RAW;
-- create database if not exists ANALYTICS;
-- create schema if not exists RAW.CHEDDR_WEDDR;
-- create schema if not exists ANALYTICS.CHEDDR_WEDDR;

-- -- Create warehouses
-- create warehouse if not exists LOADING warehouse_size = 'XSMALL';
-- create warehouse if not exists TRANSFORMING warehouse_size = 'XSMALL';
-- create warehouse if not exists REPORTING warehouse_size = 'XSMALL'; 

-- -- Create roles
-- create role if not exists LOADER;
-- create role if not exists TRANSFORMER;
-- create role if not exists REPORTER;

-- -- Role permissions
-- -- Warehouses
-- GRANT USAGE ON WAREHOUSE LOADING      TO ROLE LOADER;
-- GRANT USAGE ON WAREHOUSE TRANSFORMING TO ROLE TRANSFORMER;
-- GRANT USAGE ON WAREHOUSE REPORTING    TO ROLE REPORTER;

-- -- Databases
-- GRANT USAGE ON DATABASE RAW        TO ROLE LOADER;
-- GRANT USAGE ON DATABASE RAW        TO ROLE TRANSFORMER;

-- GRANT USAGE ON DATABASE ANALYTICS  TO ROLE TRANSFORMER;
-- GRANT USAGE ON DATABASE ANALYTICS  TO ROLE REPORTER;

-- -- RAW: loader builds/owns; transformer only reads
-- GRANT USAGE ON ALL SCHEMAS    IN DATABASE RAW TO ROLE LOADER;
-- GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RAW TO ROLE LOADER;
-- GRANT CREATE SCHEMA ON DATABASE RAW TO ROLE LOADER;  -- if your loaders create connector-specific schemas

-- GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
--   ON ALL SCHEMAS    IN DATABASE RAW TO ROLE LOADER;
-- GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
--   ON FUTURE SCHEMAS IN DATABASE RAW TO ROLE LOADER;

-- GRANT USAGE ON ALL SCHEMAS    IN DATABASE RAW TO ROLE TRANSFORMER;
-- GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RAW TO ROLE TRANSFORMER;
-- GRANT SELECT ON ALL TABLES     IN DATABASE RAW TO ROLE TRANSFORMER;
-- GRANT SELECT ON FUTURE TABLES  IN DATABASE RAW TO ROLE TRANSFORMER;
-- GRANT SELECT ON ALL VIEWS      IN DATABASE RAW TO ROLE TRANSFORMER;
-- GRANT SELECT ON FUTURE VIEWS   IN DATABASE RAW TO ROLE TRANSFORMER;

-- -- ANALYTICS: transformer builds/owns; reporter only reads
-- GRANT USAGE ON ALL SCHEMAS    IN DATABASE ANALYTICS TO ROLE TRANSFORMER;
-- GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ANALYTICS TO ROLE TRANSFORMER;
-- GRANT CREATE SCHEMA ON DATABASE ANALYTICS TO ROLE TRANSFORMER;

-- GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE STAGE
--   ON ALL SCHEMAS    IN DATABASE ANALYTICS TO ROLE TRANSFORMER;
-- GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, CREATE STAGE
--   ON FUTURE SCHEMAS IN DATABASE ANALYTICS TO ROLE TRANSFORMER;

-- GRANT USAGE ON ALL SCHEMAS    IN DATABASE ANALYTICS TO ROLE REPORTER;
-- GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ANALYTICS TO ROLE REPORTER;
-- GRANT SELECT ON ALL TABLES     IN DATABASE ANALYTICS TO ROLE REPORTER;
-- GRANT SELECT ON FUTURE TABLES  IN DATABASE ANALYTICS TO ROLE REPORTER;
-- GRANT SELECT ON ALL VIEWS      IN DATABASE ANALYTICS TO ROLE REPORTER;
-- GRANT SELECT ON FUTURE VIEWS   IN DATABASE ANALYTICS TO ROLE REPORTER;
