transform:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: JVADHFE-NF81035

      # User/password auth
      user: shansali2
      password: Skylight123Awesome876

      role: transformer
      database: analytics
      warehouse: transform
      schema: cheddr_weddr
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: True # default: true
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None